# -*- coding: utf-8 -*-
"""lab4_EMG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSmpe1Axp-oI2AlN0BWyjekg15jHA4pV
"""

!pip install opensignalsreader

from google.colab import drive
drive.mount('/content/drive')

baseline_brazo = "/content/drive/MyDrive/senalesBitalino/BASELINEBRAZO.txt"
baseline_mano = "/content/drive/MyDrive/senalesBitalino/BASELINEMANO.txt"

emg_mano = "/content/drive/MyDrive/senalesBitalino/PRUEBAMANO3.txt"
emg_brazo ="/content/drive/MyDrive/senalesBitalino/PRUEBABRAZO1.txt"

import opensignalsreader as osr
from opensignalsreader import OpenSignalsReader
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import butter, lfilter, welch

# Read OpenSignals file and plot all signals for baseline (hand and arm) and EMG (hand and arm)

# Lista de todas las rutas de los archivos de señales
signal_files = [
    baseline_mano,
    baseline_brazo,
    emg_mano,
    emg_brazo
]

# Iterar sobre cada archivo y plotear todas sus señales
for file_path in signal_files:
    print(f"Plotting signals from: {file_path}")
    acq = OpenSignalsReader(file_path, show=True)

# Definimos la frecuencia de muestreo (fs).
fs = 1000

for file_path in signal_files:
    # Extraemos el nombre del archivo
    nombre_archivo = file_path.split('/')[-1].replace('.txt', '')
    print(f"--- Procesando y graficando: {nombre_archivo} ---")

    # Leer el archivo
    acq = osr.OpenSignalsReader(file_path)

    # Buscamos automáticamente en qué canal de Bitalino hay datos
    senial = None
    canal_encontrado = ""

    for ch in range(1, 7):
        try:
            senial = acq.signal(ch)
            canal_encontrado = f"Canal {ch}"
            break
        except:
            continue

    if senial is None:
        print(f"No se encontraron canales válidos (1-6) en {file_path}")
        continue

    # Restamos la media para centrar la señal
    senial = senial - np.mean(senial)

    # -------------------------------------------------
    # REDUCIMOS EL TAMAÑO AQUÍ: figsize=(ancho, alto)
    # -------------------------------------------------
    fig, axs = plt.subplots(3, 1, figsize=(8, 7))

    # Título principal (le bajé un poquito el tamaño de la letra a 16)
    fig.suptitle(f'Análisis de Señal: {nombre_archivo} ({canal_encontrado})',
                 fontsize=16, fontweight='bold', color='darkblue')

    # Ajustamos el espaciado (pad más pequeño) para este nuevo tamaño
    fig.tight_layout(pad=3.0, rect=[0, 0, 1, 0.95])

    # -------------------------------------------------
    # 1. SEÑAL EN EL TIEMPO (RAW)
    # -------------------------------------------------
    tiempo = np.arange(len(senial)) / fs
    axs[0].plot(tiempo, senial, color='royalblue', linewidth=0.8)
    axs[0].set_title('Señal en el Dominio del Tiempo', fontsize=12, fontweight='bold')
    axs[0].set_xlabel('Tiempo [s]', fontsize=10)
    axs[0].set_ylabel('Amplitud [mV]', fontsize=10)
    axs[0].grid(True, linestyle='--', alpha=0.7)

    # -------------------------------------------------
    # 2. TRANSFORMADA RÁPIDA DE FOURIER (FFT)
    # -------------------------------------------------
    N = len(senial)
    fft_vals = np.fft.fft(senial)
    fft_freqs = np.fft.fftfreq(N, 1/fs)

    half_N = N // 2
    axs[1].plot(fft_freqs[:half_N], np.abs(fft_vals)[:half_N], color='crimson', linewidth=0.8)
    axs[1].set_title('Espectro de Frecuencia (FFT)', fontsize=12, fontweight='bold')
    axs[1].set_xlabel('Frecuencia [Hz]', fontsize=10)
    axs[1].set_ylabel('Magnitud', fontsize=10)
    axs[1].set_xlim(0, fs/2)
    axs[1].grid(True, linestyle='--', alpha=0.7)

    # -------------------------------------------------
    # 3. ESPECTROGRAMA (STFT)
    # -------------------------------------------------
    Pxx, freqs, bins, im = axs[2].specgram(senial, NFFT=256, Fs=fs, noverlap=128, cmap='viridis')
    axs[2].set_title('Espectrograma (STFT)', fontsize=12, fontweight='bold')
    axs[2].set_xlabel('Tiempo [s]', fontsize=10)
    axs[2].set_ylabel('Frecuencia [Hz]', fontsize=10)

    cbar = fig.colorbar(im, ax=axs[2])
    cbar.set_label('Densidad de Potencia (dB)', rotation=270, labelpad=15)

    plt.show()