# -*- coding: utf-8 -*-
"""Lab5_bitalino.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FZiU6gw8WHQyYFcJVU5C38rW--ph-qMJ
"""

# ============================================================
# ECG SIGNAL PROCESSING - LABORATORY 4
# BITalino / OpenSignals
#
# Activity 1:
#   Baseline in Lead I, II, III
#   Hyperventilation repetition 1 in Lead I, II, III
#   Hyperventilation repetition 2 in Lead I, II, III
#
# Activity 2:
#   Post-exercise ECG in Lead I, II, III
#
# Activity 3:
#   Breath-holding / apnea ECG in Lead I, II, III
# ============================================================

!pip install opensignalsreader

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import opensignalsreader as osr
from opensignalsreader import OpenSignalsReader

from scipy.signal import butter, filtfilt, iirnotch, find_peaks
from IPython.display import display

# ============================================================
# 1. GENERAL CONFIGURATION
# ============================================================

# Sampling frequency used in OpenSignals.
# Change this value if your acquisition used another sampling rate.
FS_DEFAULT = 1000

# ECG filtering parameters
LOWCUT = 0.5        # Hz
HIGHCUT = 40        # Hz
NOTCH_FREQ = 60     # Hz
NOTCH_Q = 30

# If you know the ECG channel, write it here.
# Example: PREFERRED_CHANNEL = 1
# If you do not know it, leave it as None.
PREFERRED_CHANNEL = None

# Output folder
OUTPUT_DIR = "/content/drive/MyDrive/Lab_5/Señales"
os.makedirs(OUTPUT_DIR, exist_ok=True)


# ============================================================
# 2. FILE PATHS
# Replace these paths with your real OpenSignals .txt files
# ============================================================

# ------------------------------------------------------------
# ACTIVITY 1: Baseline + hyperventilation
# ------------------------------------------------------------

activity_1_files = {
    # Baseline ECG - 3 leads
    "A1_baseline_lead_I": "/content/drive/MyDrive/Lab_5/Señales/BasalDer1.txt",
    "A1_baseline_lead_II": "/content/drive/MyDrive/Lab_5/Señales/BasalDer2.txt",
    "A1_baseline_lead_III": "/content/drive/MyDrive/Lab_5/Señales/BasalDer3.txt",

    # Hyperventilation - repetition 1
    "A1_hyperventilation_rep1_lead_I": "/content/drive/MyDrive/Lab_5/Señales/der1.txt",
    "A1_hyperventilation_rep1_lead_II": "/content/drive/MyDrive/Lab_5/Señales/der2.txt",
    "A1_hyperventilation_rep1_lead_III": "/content/drive/MyDrive/Lab_5/Señales/der3.txt",

    # Hyperventilation - repetition 2
    "A1_hyperventilation_rep2_lead_I": "/content/drive/MyDrive/Lab_5/Señales/2der1.txt",
    "A1_hyperventilation_rep2_lead_II": "/content/drive/MyDrive/Lab_5/Señales/2der2.txt",
    "A1_hyperventilation_rep2_lead_III": "/content/drive/MyDrive/Lab_5/Señales/2der3.txt",
}


# ------------------------------------------------------------
# ACTIVITY 2: Post-exercise
# ------------------------------------------------------------

activity_2_files = {
    "A2_post_exercise_lead_I": "/content/drive/MyDrive/Lab_5/Señales/act_Der1.txt",
    "A2_post_exercise_lead_II": "/content/drive/MyDrive/Lab_5/Señales/Act_Der2.txt",
    "A2_post_exercise_lead_III": "/content/drive/MyDrive/Lab_5/Señales/Act_Der3.txt",
}


# ------------------------------------------------------------
# ACTIVITY 3: Breath-holding / apnea
# ------------------------------------------------------------

activity_3_files = {
    "A3_apnea_lead_I": "/content/drive/MyDrive/Lab_5/Señales/Activity_3_Breath_Holding_Apnea/Hipo_Der1.txt",
    "A3_apnea_lead_II": "/content/drive/MyDrive/Lab_5/Señales/Activity_3_Breath_Holding_Apnea/Hipo_Der2.txt",
    "A3_apnea_lead_III": "/content/drive/MyDrive/Lab_5/Señales/Activity_3_Breath_Holding_Apnea/Hipo_Der3.txt",
}

print('=' * 80)
print('VERIFICACIÓN DE RUTAS DE ARCHIVOS')
print('=' * 80)

print(f"Directorio de salida configurado: {OUTPUT_DIR}")

print("\nArchivos encontrados en el directorio de salida:")
try:
    for f in os.listdir(OUTPUT_DIR):
        print(f" - {f}")
except FileNotFoundError:
    print(f"El directorio {OUTPUT_DIR} no fue encontrado. Asegúrate de que exista y que Google Drive esté montado correctamente.")

print("\nVerificando la existencia de archivos en activity_1_files:")
for record_name, file_path in activity_3_files.items():
    if os.path.exists(file_path):
        print(f" - {record_name}: {file_path} (EXISTE)")
    else:
        print(f" - {record_name}: {file_path} (NO ENCONTRADO)")

# ============================================================
# 3. HELPER FUNCTIONS
# ============================================================

def clean_name(name):
    """
    Convert a record name into a safe filename.
    """
    return (
        name.replace(" ", "_")
            .replace("/", "_")
            .replace("\\", "_")
            .replace(":", "_")
    )


def get_valid_signal(acq, preferred_channel=None):
    """
    Extract the signal from the preferred channel.
    If preferred_channel is None, search automatically from channel 1 to 6.
    """
    if preferred_channel is not None:
        try:
            signal = np.asarray(acq.signal(preferred_channel), dtype=float).flatten()
            if len(signal) > 0 and np.nanstd(signal) > 0:
                return signal, preferred_channel
        except Exception as e:
            print(f"Preferred channel {preferred_channel} was not valid: {e}")

    for ch in range(1, 7):
        try:
            signal = np.asarray(acq.signal(ch), dtype=float).flatten()
            if len(signal) > 0 and np.nanstd(signal) > 0:
                return signal, ch
        except:
            continue

    return None, None


def notch_filter(signal, notch_freq, fs, q=30):
    """
    Apply a notch filter to reduce powerline noise.
    """
    nyquist = fs / 2

    if notch_freq >= nyquist:
        return signal

    w0 = notch_freq / nyquist
    b, a = iirnotch(w0, q)
    filtered_signal = filtfilt(b, a, signal)

    return filtered_signal


def bandpass_filter(signal, lowcut, highcut, fs, order=4):
    """
    Apply a Butterworth bandpass filter for ECG.
    """
    nyquist = fs / 2

    if highcut >= nyquist:
        highcut = nyquist * 0.90

    low = lowcut / nyquist
    high = highcut / nyquist

    b, a = butter(order, [low, high], btype="band")
    filtered_signal = filtfilt(b, a, signal)

    return filtered_signal


def preprocess_ecg(raw_signal, fs):
    """
    ECG preprocessing:
    1. Remove NaN values
    2. Remove DC offset
    3. Apply notch filter
    4. Apply bandpass filter
    """
    signal = np.asarray(raw_signal, dtype=float)
    signal = np.nan_to_num(signal)

    centered_signal = signal - np.mean(signal)

    notched_signal = notch_filter(
        signal=centered_signal,
        notch_freq=NOTCH_FREQ,
        fs=fs,
        q=NOTCH_Q
    )

    filtered_signal = bandpass_filter(
        signal=notched_signal,
        lowcut=LOWCUT,
        highcut=HIGHCUT,
        fs=fs,
        order=4
    )

    return centered_signal, filtered_signal


def detect_r_peaks(filtered_ecg, fs):
    """
    Detect R peaks using scipy.find_peaks.
    The function also checks if the ECG signal is inverted.
    """
    signal = np.asarray(filtered_ecg)

    positive_amplitude = np.percentile(signal, 99)
    negative_amplitude = abs(np.percentile(signal, 1))

    if negative_amplitude > positive_amplitude:
        signal_for_detection = -signal
        polarity = "inverted"
    else:
        signal_for_detection = signal
        polarity = "normal"

    # Minimum distance between R peaks.
    # 0.35 s corresponds approximately to a maximum HR of 171 bpm.
    min_distance = int(0.35 * fs)

    # Adaptive prominence based on signal standard deviation.
    prominence = 0.5 * np.std(signal_for_detection)

    peaks, properties = find_peaks(
        signal_for_detection,
        distance=min_distance,
        prominence=prominence
    )

    return peaks, properties, polarity


def compute_ecg_metrics(peaks, fs, duration_s):
    """
    Compute descriptive ECG metrics.
    HRV metrics are only descriptive because the recordings are short.
    """
    metrics = {
        "duration_s": duration_s,
        "number_of_r_peaks": len(peaks),
        "mean_hr_bpm": np.nan,
        "median_hr_bpm": np.nan,
        "mean_rr_s": np.nan,
        "sdnn_ms": np.nan,
        "rmssd_ms": np.nan,
        "pnn50_percent": np.nan
    }

    if len(peaks) < 2:
        return metrics

    rr_intervals = np.diff(peaks) / fs

    # Keep physiologically plausible RR intervals
    rr_intervals = rr_intervals[
        (rr_intervals >= 0.30) & (rr_intervals <= 2.00)
    ]

    if len(rr_intervals) < 1:
        return metrics

    hr_values = 60 / rr_intervals

    metrics["mean_hr_bpm"] = np.mean(hr_values)
    metrics["median_hr_bpm"] = np.median(hr_values)
    metrics["mean_rr_s"] = np.mean(rr_intervals)

    if len(rr_intervals) > 1:
        metrics["sdnn_ms"] = np.std(rr_intervals, ddof=1) * 1000

    if len(rr_intervals) > 2:
        rr_diff = np.diff(rr_intervals)
        metrics["rmssd_ms"] = np.sqrt(np.mean(rr_diff ** 2)) * 1000
        metrics["pnn50_percent"] = (
            np.sum(np.abs(rr_diff) > 0.05) / len(rr_diff)
        ) * 100

    return metrics


def plot_ecg_analysis(record_name, raw_centered, filtered_ecg, peaks, fs, output_dir):
    """
    Create and save ECG plots:
    1. Raw centered ECG
    2. Filtered ECG with R peaks
    3. FFT
    4. Spectrogram
    """
    time = np.arange(len(raw_centered)) / fs

    fig, axs = plt.subplots(4, 1, figsize=(12, 12))
    fig.suptitle(f"ECG Analysis - {record_name}", fontsize=16, fontweight="bold")

    # --------------------------------------------------------
    # 1. Raw centered ECG
    # --------------------------------------------------------
    axs[0].plot(time, raw_centered, linewidth=0.8)
    axs[0].set_title("Raw ECG signal centered")
    axs[0].set_xlabel("Time [s]")
    axs[0].set_ylabel("Amplitude [a.u.]")
    axs[0].grid(True, linestyle="--", alpha=0.6)

    # --------------------------------------------------------
    # 2. Filtered ECG with R peaks
    # --------------------------------------------------------
    axs[1].plot(time, filtered_ecg, linewidth=0.8, label="Filtered ECG")

    if len(peaks) > 0:
        axs[1].plot(
            time[peaks],
            filtered_ecg[peaks],
            "x",
            label="Detected R peaks"
        )

    axs[1].set_title("Filtered ECG with detected R peaks")
    axs[1].set_xlabel("Time [s]")
    axs[1].set_ylabel("Amplitude [a.u.]")
    axs[1].legend()
    axs[1].grid(True, linestyle="--", alpha=0.6)

    # --------------------------------------------------------
    # 3. FFT
    # --------------------------------------------------------
    N = len(filtered_ecg)
    fft_values = np.fft.fft(filtered_ecg)
    fft_freqs = np.fft.fftfreq(N, 1 / fs)

    half_N = N // 2

    axs[2].plot(
        fft_freqs[:half_N],
        np.abs(fft_values)[:half_N],
        linewidth=0.8
    )

    axs[2].set_title("Frequency spectrum - FFT")
    axs[2].set_xlabel("Frequency [Hz]")
    axs[2].set_ylabel("Magnitude")
    axs[2].set_xlim(0, min(80, fs / 2))
    axs[2].grid(True, linestyle="--", alpha=0.6)

    # --------------------------------------------------------
    # 4. Spectrogram
    # --------------------------------------------------------
    nfft = 512

    if len(filtered_ecg) <= nfft:
        nfft = max(64, len(filtered_ecg) // 4)

    noverlap = nfft // 2

    if nfft > 0 and len(filtered_ecg) > nfft:
        Pxx, freqs, bins, im = axs[3].specgram(
            filtered_ecg,
            NFFT=nfft,
            Fs=fs,
            noverlap=noverlap
        )

        axs[3].set_ylim(0, min(80, fs / 2))
        cbar = fig.colorbar(im, ax=axs[3])
        cbar.set_label("Power [dB]")

    else:
        axs[3].text(
            0.5,
            0.5,
            "Signal too short for spectrogram",
            ha="center",
            va="center",
            transform=axs[3].transAxes
        )

    axs[3].set_title("Spectrogram - STFT")
    axs[3].set_xlabel("Time [s]")
    axs[3].set_ylabel("Frequency [Hz]")

    plt.tight_layout(rect=[0, 0, 1, 0.96])

    figure_name = clean_name(record_name) + ".png"
    figure_path = os.path.join(output_dir, figure_name)

    plt.savefig(figure_path, dpi=300, bbox_inches="tight")
    plt.show()

    return figure_path


def process_record(record_name, file_path, activity_name):
    """
    Process a single OpenSignals ECG file.
    """
    activity_output_dir = os.path.join(OUTPUT_DIR, clean_name(activity_name))
    os.makedirs(activity_output_dir, exist_ok=True)

    if "REPLACE" in file_path:
        print(f"[SKIPPED] Replace file path first: {record_name}")
        return None

    if not os.path.exists(file_path):
        print(f"[SKIPPED] File not found: {record_name}")
        print(f"Path: {file_path}")
        return None

    print("\n" + "-" * 70)
    print(f"Processing record: {record_name}")
    print(f"Activity: {activity_name}")
    print(f"Path: {file_path}")

    acq = osr.OpenSignalsReader(file_path)

    raw_signal, channel = get_valid_signal(
        acq=acq,
        preferred_channel=PREFERRED_CHANNEL
    )

    if raw_signal is None:
        print(f"No valid signal found for {record_name}")
        return None

    fs = FS_DEFAULT
    duration_s = len(raw_signal) / fs

    print(f"Detected channel: {channel}")
    print(f"Sampling frequency used: {fs} Hz")
    print(f"Duration: {duration_s:.2f} s")

    raw_centered, filtered_ecg = preprocess_ecg(
        raw_signal=raw_signal,
        fs=fs
    )

    peaks, properties, polarity = detect_r_peaks(
        filtered_ecg=filtered_ecg,
        fs=fs
    )

    metrics = compute_ecg_metrics(
        peaks=peaks,
        fs=fs,
        duration_s=duration_s
    )

    figure_path = plot_ecg_analysis(
        record_name=record_name,
        raw_centered=raw_centered,
        filtered_ecg=filtered_ecg,
        peaks=peaks,
        fs=fs,
        output_dir=activity_output_dir
    )

    result = {
        "activity": activity_name,
        "record_name": record_name,
        "file_path": file_path,
        "channel": channel,
        "fs_hz": fs,
        "polarity": polarity,
        "figure_path": figure_path,
        **metrics
    }

    return result


def process_activity(activity_name, files_dict):
    """
    Process all ECG files from one activity.
    """
    print("\n" + "=" * 80)
    print(f"PROCESSING {activity_name}")
    print("=" * 80)

    results = []

    for record_name, file_path in files_dict.items():
        result = process_record(
            record_name=record_name,
            file_path=file_path,
            activity_name=activity_name
        )

        if result is not None:
            results.append(result)

    df = pd.DataFrame(results)

    activity_output_dir = os.path.join(OUTPUT_DIR, clean_name(activity_name))
    os.makedirs(activity_output_dir, exist_ok=True)

    if len(df) > 0:
        csv_path = os.path.join(
            activity_output_dir,
            clean_name(activity_name) + "_summary.csv"
        )

        df.to_csv(csv_path, index=False)

        print("\nActivity summary:")
        display(df)

        print(f"Summary CSV saved at: {csv_path}")

    else:
        print("No valid files were processed for this activity.")

    return df


def plot_activity_hr_summary(df, activity_name):
    """
    Plot mean heart rate summary for one activity.
    """
    if df is None or len(df) == 0:
        print(f"No data available for {activity_name}")
        return

    valid_df = df.dropna(subset=["mean_hr_bpm"])

    if len(valid_df) == 0:
        print(f"No valid HR values available for {activity_name}")
        return

    plt.figure(figsize=(12, 5))
    plt.bar(valid_df["record_name"], valid_df["mean_hr_bpm"])
    plt.xticks(rotation=45, ha="right")
    plt.ylabel("Mean heart rate [bpm]")
    plt.title(f"Mean heart rate comparison - {activity_name}")
    plt.grid(axis="y", linestyle="--", alpha=0.6)
    plt.tight_layout()

    activity_output_dir = os.path.join(OUTPUT_DIR, clean_name(activity_name))
    os.makedirs(activity_output_dir, exist_ok=True)

    figure_path = os.path.join(
        activity_output_dir,
        clean_name(activity_name) + "_heart_rate_summary.png"
    )

    plt.savefig(figure_path, dpi=300, bbox_inches="tight")
    plt.show()

    print(f"Heart rate summary plot saved at: {figure_path}")


def show_raw_opensignals(files_dict):
    """
    Optional function to show raw OpenSignals visualization.
    """
    for record_name, file_path in files_dict.items():
        if "REPLACE" in file_path or not os.path.exists(file_path):
            print(f"[SKIPPED] {record_name}")
            continue

        print(f"Showing raw OpenSignals plot for: {record_name}")
        OpenSignalsReader(file_path, show=True)

# ============================================================
# 4. PROCESS ACTIVITY 1
# Baseline + hyperventilation
# ============================================================

activity_1_results = process_activity(
    activity_name="Activity_1_Baseline_and_Hyperventilation",
    files_dict=activity_1_files
)

plot_activity_hr_summary(
    df=activity_1_results,
    activity_name="Activity_1_Baseline_and_Hyperventilation"
)

# ============================================================
# 5. PROCESS ACTIVITY 2
# Post-exercise
# ============================================================

activity_2_results = process_activity(
    activity_name="Activity_2_Post_Exercise",
    files_dict=activity_2_files
)

plot_activity_hr_summary(
    df=activity_2_results,
    activity_name="Activity_2_Post_Exercise"
)

# ============================================================
# 6. PROCESS ACTIVITY 3
# Breath-holding / apnea
# ============================================================

activity_3_results = process_activity(
    activity_name="Activity_3_Breath_Holding_Apnea",
    files_dict=activity_3_files
)

plot_activity_hr_summary(
    df=activity_3_results,
    activity_name="Activity_3_Breath_Holding_Apnea"
)

# ============================================================
# 7. GLOBAL SUMMARY
# ============================================================

dataframes = []

if activity_1_results is not None and len(activity_1_results) > 0:
    dataframes.append(activity_1_results)

if activity_2_results is not None and len(activity_2_results) > 0:
    dataframes.append(activity_2_results)

if activity_3_results is not None and len(activity_3_results) > 0:
    dataframes.append(activity_3_results)

if len(dataframes) > 0:
    global_results = pd.concat(dataframes, ignore_index=True)

    global_csv_path = os.path.join(
        OUTPUT_DIR,
        "Lab4_ECG_global_summary.csv"
    )

    global_results.to_csv(global_csv_path, index=False)

    print("\n" + "=" * 80)
    print("GLOBAL SUMMARY")
    print("=" * 80)

    display(global_results)

    print(f"Global summary CSV saved at: {global_csv_path}")

else:
    global_results = pd.DataFrame()
    print("No global results available.")

# ============================================================
# 8. GLOBAL HEART RATE COMPARISON
# ============================================================

if len(global_results) > 0:
    valid_global = global_results.dropna(subset=["mean_hr_bpm"])

    if len(valid_global) > 0:
        plt.figure(figsize=(15, 6))
        plt.bar(valid_global["record_name"], valid_global["mean_hr_bpm"])
        plt.xticks(rotation=60, ha="right")
        plt.ylabel("Mean heart rate [bpm]")
        plt.title("Global mean heart rate comparison - ECG Laboratory 4")
        plt.grid(axis="y", linestyle="--", alpha=0.6)
        plt.tight_layout()

        global_hr_path = os.path.join(
            OUTPUT_DIR,
            "Lab4_ECG_global_heart_rate_comparison.png"
        )

        plt.savefig(global_hr_path, dpi=300, bbox_inches="tight")
        plt.show()

        print(f"Global HR comparison plot saved at: {global_hr_path}")

    else:
        print("No valid global heart rate values available.")
else:
    print("No global results to plot.")


# ============================================================
# 9. BASELINE VS CONDITIONS COMPARISON
# This section is useful because only Activity 1 has baseline.
# ============================================================

if len(global_results) > 0:

    baseline_df = global_results[
        global_results["record_name"].str.contains("baseline", case=False, na=False)
    ]

    condition_df = global_results[
        ~global_results["record_name"].str.contains("baseline", case=False, na=False)
    ]

    print("\n" + "=" * 80)
    print("BASELINE RECORDS")
    print("=" * 80)
    display(baseline_df)

    print("\n" + "=" * 80)
    print("NON-BASELINE CONDITIONS")
    print("=" * 80)
    display(condition_df)

    if len(baseline_df) > 0 and len(condition_df) > 0:

        baseline_mean_hr = baseline_df["mean_hr_bpm"].mean()

        comparison_table = condition_df.copy()
        comparison_table["baseline_mean_hr_bpm"] = baseline_mean_hr
        comparison_table["delta_hr_vs_baseline_bpm"] = (
            comparison_table["mean_hr_bpm"] - baseline_mean_hr
        )

        comparison_csv_path = os.path.join(
            OUTPUT_DIR,
            "Lab4_ECG_baseline_vs_conditions.csv"
        )

        comparison_table.to_csv(comparison_csv_path, index=False)

        print("\n" + "=" * 80)
        print("BASELINE VS CONDITIONS COMPARISON")
        print("=" * 80)

        display(comparison_table)

        print(f"Comparison CSV saved at: {comparison_csv_path}")

        valid_comparison = comparison_table.dropna(
            subset=["delta_hr_vs_baseline_bpm"]
        )

        if len(valid_comparison) > 0:
            plt.figure(figsize=(14, 6))
            plt.bar(
                valid_comparison["record_name"],
                valid_comparison["delta_hr_vs_baseline_bpm"]
            )
            plt.axhline(0, linestyle="--", linewidth=1)
            plt.xticks(rotation=60, ha="right")
            plt.ylabel("Delta HR vs baseline [bpm]")
            plt.title("Heart rate difference relative to Activity 1 baseline")
            plt.grid(axis="y", linestyle="--", alpha=0.6)
            plt.tight_layout()

            delta_hr_path = os.path.join(
                OUTPUT_DIR,
                "Lab4_ECG_delta_hr_vs_baseline.png"
            )

            plt.savefig(delta_hr_path, dpi=300, bbox_inches="tight")
            plt.show()

            print(f"Delta HR plot saved at: {delta_hr_path}")

else:
    print("No data available for baseline comparison.")